# Generated by Django 4.2.1 on 2023-06-26 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_hubapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='user',
        ),
        migrations.AlterField(
            model_name='applicants',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
