# Generated by Django 4.2.1 on 2023-06-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hubapp', '0002_remove_applicants_user_alter_applicants_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.BigIntegerField(),
        ),
    ]
