# Generated by Django 4.2.1 on 2023-07-02 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_hubapp', '0009_alter_job_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('resume', models.ImageField(upload_to='')),
                ('apply_date', models.DateField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_hubapp.applicants')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_hubapp.job')),
            ],
        ),
    ]
