# Generated by Django 4.2.1 on 2023-07-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hubapp', '0012_alter_application_apply_date_alter_job_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
