# Generated by Django 4.2.1 on 2023-07-17 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_hubapp', '0016_alter_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_hubapp.applicants'),
        ),
    ]
