# Generated by Django 4.2.1 on 2023-07-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_hubapp', '0017_job_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='applicant',
        ),
    ]
