# Generated by Django 4.2.1 on 2023-07-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hubapp', '0020_remove_applicants_profile_remove_applicants_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='profile',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
