# Generated by Django 4.2.1 on 2023-07-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_hubapp', '0024_alter_application_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to=''),
        ),
    ]
